[package]
name = "command_derive"
version = "0.1.0"
authors = ["atune <atune313@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.40"
proc-macro2 = "1.0.27"
quote = "1.0.9"
serenity = "0.10.7"
syn = "1.0.72"

[dependencies.framework]
path = "../framework"